/*************************************************************************
*  Copyright (C) 2012 by François Kneib   francois.kneib@gmail.com       *
*  Copyright (C) 2012 by Bruno Chareyre   bruno.chareyre@grenoble-inp.fr     *
*  This program is free software; it is licensed under the terms of the  *
*  GNU General Public License v2 or later. See file LICENSE for details. *
*************************************************************************/

#include "MembraneNode.hpp"

namespace yade{
	//*****************************************4-14
	//MembraneNode::~MembraneNode() { }
	YADE_PLUGIN((MembraneNode)(MembraneMat)(NodeFrictPhys));

	void Bo1_MembraneNode_Aabb::go(const shared_ptr<Shape>& cm, shared_ptr<Bound>& bv, const Se3r& se3, const Body* /*b*/)
	{
		MembraneNode* MN = static_cast<MembraneNode*>(cm.get());
		if (!bv) { bv = shared_ptr<Bound>(new Aabb); }
		Aabb*    aabb = static_cast<Aabb*>(bv.get());
		Vector3r halfSize = (aabbEnlargeFactor > 0 ? aabbEnlargeFactor : 1.) * Vector3r(MN->radius, MN->radius, MN->radius);
		if (!scene->isPeriodic) {
			aabb->min = se3.position - halfSize;
			aabb->max = se3.position + halfSize;
			return;
		}
	}
	YADE_PLUGIN((Bo1_MembraneNode_Aabb));
	//**************************3  Iphys Functors ************************//
	void Ip2_MembraneMat_MembraneMat_NodeFrictPhys::go(
		const shared_ptr<Material>& b1 // MembraneMat
		,
		const shared_ptr<Material>& b2 // MembraneMat
		,
		const shared_ptr<Interaction>& interaction)
	{
		MembraneMat* mat1 = static_cast<MembraneMat*>(b1.get());
		MembraneMat* mat2 = static_cast<MembraneMat*>(b2.get());

		if (interaction->phys) return;

		//LOG_TRACE("Ip2_LineMat_LineMat_LinePhys::go - create interaction physics");

		ScGeom6D*    geom = YADE_CAST<ScGeom6D*>(interaction->geom.get());
		assert(geom);

		shared_ptr<NodeFrictPhys> contactPhysics(new NodeFrictPhys());//新建NodeFrictPhys()对象
		Real R1 = geom->radius1;
		Real R2 = geom->radius2;
		Real                 initD =/* R1+ R2-*/geom->penetrationDepth;//初始距离
		contactPhysics->normalForce = Vector3r::Zero();//法向力

		//MembraneMat* mat1 = static_cast<MembraneMat*>(b1.get());
		//MembraneMat* mat2 = static_cast<MembraneMat*>(b2.get());

		Real          Ea = mat1->young;
		Real          Eb = mat2->young;
		Real          Va = mat1->poisson;
		Real          Vb = mat2->poisson;
		Real          Da = R1;
		Real          Db = R2;
		Real          fa = mat1->frictionAngle;
		Real          fb = mat2->frictionAngle;
		Real          Kn = 2.0 * Ea * Da * Eb * Db / (Ea * Da + Eb * Db); //harmonic average of two stiffnesses
		Real          frictionAngle = math::min(fa, fb);
		Real Ks;
		if (Va && Vb)
			Ks = 2.0 * Ea * Da * Va * Eb * Db * Vb / (Ea * Da * Va + Eb * Db * Vb); //harmonic average of two stiffnesses with ks=V*kn for each sphere
		else
			Ks = 0;
		contactPhysics->tangensOfFrictionAngle = math::tan(frictionAngle);
		contactPhysics->kn = Kn;//法向
		contactPhysics->ks = Ks;//切向
		contactPhysics->normalLimit = NormalStrength;
		//contactPhysics->momentRotationLaw = (mat1->momentRotationLaw && mat2->momentRotationLaw);

		contactPhysics->initD = initD;
		contactPhysics->Kn = mat1->Kn;
		contactPhysics->Ks = mat1->Ks;
		interaction->phys = contactPhysics;//传址

	}
	YADE_PLUGIN((Ip2_MembraneMat_MembraneMat_NodeFrictPhys));


	//**************************3  Igeom Functors ************************//
	bool Ig2_MembraneNode_MembraneNode_ScGeom6D::go(
		const shared_ptr<Shape>&       cm1,
		const shared_ptr<Shape>&       cm2,
		const State&                   state1,
		const State&                   state2,
		const Vector3r&                shift2,
		const bool&                    force,
		const shared_ptr<Interaction>& c)
	{
		bool isNew = !c->geom;
		bool hasIg2 = Ig2_Sphere_Sphere_ScGeom::go(cm1, cm2, state1, state2, shift2, force, c);
		if (hasIg2) { //the 3 DOFS from ScGeom are updated here
			if (isNew) { //generate a 6DOF interaction from the 3DOF one generated by Ig2_Sphere_Sphere_ScGeom
				shared_ptr<ScGeom6D> sc(new ScGeom6D());
				*(YADE_PTR_CAST<ScGeom>(sc)) = *(YADE_PTR_CAST<ScGeom>(c->geom));//=重载,赋值成员变量 scgeom6d.norm=scgeom.norm
				c->geom = sc;
			}
			if (updateRotations) YADE_PTR_CAST<ScGeom6D>(c->geom)->precomputeRotations(state1, state2, isNew, creep);
			return true;
		}
		else
			return false;
	}

	bool Ig2_MembraneNode_MembraneNode_ScGeom6D::goReverse(
		const shared_ptr<Shape>&       cm1,
		const shared_ptr<Shape>&       cm2,
		const State&                   state1,
		const State&                   state2,
		const Vector3r&                shift2,
		const bool&                    force,
		const shared_ptr<Interaction>& c)
	{
		return go(cm1, cm2, state2, state1, -shift2, force, c);
	}
	YADE_PLUGIN((Ig2_MembraneNode_MembraneNode_ScGeom6D));
	
	
	bool Ig2_MembraneNode_Sphere_ScGeom::go(
        const shared_ptr<Shape>&       cm1,
        const shared_ptr<Shape>&       cm2,
        const State&                   state1,
        const State&                   state2,
        const Vector3r&                shift2,//0
        const bool&                    force,
        const shared_ptr<Interaction>& c)
	{
	TIMING_DELTAS_START();
	const Se3r&   se31 = state1.se3;
	const Se3r&   se32 = state2.se3;
	const MembraneNode *s1 = static_cast<MembraneNode*>(cm1.get());
	const Sphere *s2 = static_cast<Sphere*>(cm2.get());
	Vector3r      normal = (se32.position + shift2) - se31.position;//方向距离向量1-2
	if (!c->isReal() && !force) { //don't fast-check distance if geometry will be updated anyway
		Real penetrationDepthSq = pow(interactionDetectionFactor * (s1->radius + s2->radius), 2) - normal.squaredNorm();//判定是否建立交互几何
		if (penetrationDepthSq < 0) {
			TIMING_DELTAS_CHECKPOINT("Ig2_Sphere_Sphere_ScGeom");
			return false;
		}
	}
	shared_ptr<ScGeom> scm;
	bool               isNew = !c->geom;
	if (!isNew) scm = YADE_PTR_CAST<ScGeom>(c->geom);
	else {
		scm     = shared_ptr<ScGeom>(new ScGeom());
		c->geom = scm;
	}
	Real norm = normal.norm();
	normal /= norm; // normal is unit vector now

	
#ifdef YADE_DEBUG
	if (norm == 0)
		throw runtime_error(("Zero distance between spheres #" + boost::lexical_cast<string>(c->getId1()) + " and #"
		                     + boost::lexical_cast<string>(c->getId2()) + ".")
		                            .c_str());
#endif
	Real penetrationDepth = s1->radius + s2->radius - norm;
	scm->contactPoint     = se31.position + (s1->radius - 0.5 * penetrationDepth) * normal; //0.5*(pt1+pt2);计算接触点位置
	scm->penetrationDepth = penetrationDepth;//穿透深度
	scm->radius1          = s1->radius;//半径1
	scm->radius2          = s2->radius;//
	scm->precompute(state1, state2, scene, c, normal, isNew, shift2, avoidGranularRatcheting);//计算剪切位移增量
	TIMING_DELTAS_CHECKPOINT("Ig2_Sphere_Sphere_ScGeom");
	return true;
	}
	
	bool Ig2_MembraneNode_Sphere_ScGeom::goReverse(
		const shared_ptr<Shape>&       cm1,
		const shared_ptr<Shape>&       cm2,
		const State&                   state1,
		const State&                   state2,
		const Vector3r&                shift2,
		const bool&                    force,
		const shared_ptr<Interaction>& c)
	{
		return go(cm2, cm1, state2, state1, -shift2, force, c);
	}
	YADE_PLUGIN((Ig2_MembraneNode_Sphere_ScGeom));

	//***************************law

	bool Law2_ScGeom6D_NodeFrictPhys_MembraneLaw::go(shared_ptr<IGeom>& ig, shared_ptr<IPhys>& ip, Interaction* contact)
	{
		//LOG_TRACE("Law2_ScGeom_WirePhys_WirePM::go - contact law");

		ScGeom6D*     geom = YADE_CAST<ScGeom6D*>(ig.get());
		NodeFrictPhys* phys = YADE_CAST<NodeFrictPhys*>(ip.get());

		//const Real&   dt = scene->dt;
		const int&    id1 = contact->getId1();
		const int&    id2 = contact->getId2();
		//Body*      b1 = Body::byId(id1, scene).get();
		//Body*      b2 = Body::byId(id2, scene).get();
		//Vector3r&     shearForceFirst = phys->shearForce;
		//if (contact->isFresh(scene)) shearForceFirst = Vector3r::Zero();
		Real un = geom->penetrationDepth;//穿透深度
		Real D = un - phys->initD;//位移变化量un<初始 D>0 受压 当前穿透深度-初始穿透深度  D>0 受压
		Real Fn = 0;

		State* st1 = Body::byId(id1, scene)->state.get();
		State* st2 = Body::byId(id2, scene)->state.get();
		Vector3r&       shearForce = geom->rotate(phys->shearForce);//变化位矢
		const Vector3r& dus = geom->shearIncrement();

		if (useK) {
			Fn = phys->Kn*D*geom->normal.norm();
			shearForce -= phys->Ks * dus;//Ks计算切向力
			if ((D < 0) && (-Fn > phys->normalLimit)) return false;//断裂
		}
		else {
			shearForce -= phys->ks * dus;//ks计算切向力
			if (un > 0) Fn = phys->kn*un*geom->normal.norm();
			else Fn = phys->Kn*D*geom->normal.norm();
		}
		phys->normalForce = Fn * geom->normal;//法向力

		//Apply the force
		applyForceAtContactPoint(
			-phys->normalForce - shearForce,
			geom->contactPoint,
			id1,
			st1->se3.position,
			id2,
			st2->se3.position + (scene->isPeriodic ? scene->cell->intrShiftPos(contact->cellDist) : Vector3r::Zero()));

		return true;
	}
	YADE_PLUGIN((Law2_ScGeom6D_NodeFrictPhys_MembraneLaw));



} // namespace yade
